language: java

sudo: required

services:
  - docker

jdk:
- openjdk8

# safelist
branches:
  only:
  - master
  - release

before_install:
  - docker run -d -e SA_PASSWORD=5F4Dt9ky9dU$ -e SQLSERVER_DATABASE=sc -e SQLSERVER_USER=user -e SQLSERVER_PASSWORD=5F4Dt9ky9dU$ -p 1433:1433 exoplatform/sqlserver:2017-CU8
  - docker run -d -e POSTGRES_PASSWORD=5F4Dt9ky9dU$ -p 5432:5432 postgres:12.1
  - docker run -d -e MYSQL_ROOT_PASSWORD=5F4Dt9ky9dU$ -e MYSQL_DATABASE=sc -p 3306:3306 mysql:8.0.19
  - docker run -d --name elasticsearch  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" paulcwarren/elasticsearch:latest
  - docker run -d -p 8983:8983 paulcwarren/solr solr-precreate solr

script:
  - mvn -B -pl '!spring-eg-content-solr' -pl '!spring-eg-content-solr-boot-starter' install --settings settings.xml
  - mvn -B -pl spring-eg-content-solr,spring-eg-content-solr-boot-starter -am install --settings settings.xml



